/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package carro_java;

import carro_java.model.Carro;
import carro_java.model.Moto;

public class App {
	public static void main(String[] args) throws Exception {
        Carro carro = new Carro("Dominic", 30, 70, "Lamborghini");
        Moto moto = new Moto("Let", 25, 60, "Harley Davidson");

        System.out.println("Piloto de Carro: " + carro.getNome() + ", Habilidade: " + carro.getNivelHabilidade()
                + ", Modelo: " + carro.getModelo());
        carro.acelerar();
        carro.frear();

        System.out.println("Piloto de Moto: " + moto.getNome() + ", Habilidade: " + moto.getNivelHabilidade()
                + ", Modelo: " + moto.getModelo());
        moto.acelerar();
        moto.frear();
    }

    public Object getGreeting() {
        return null;
    }
}